mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.lazy-loading-enabled=true
mybatis.configuration.aggressive-lazy-loading=false
# ??????????? ???????? ?????????? DAO
#logging.level.kz.hawk.fintrack.dao=DEBUG
# ??????????? ???????? ibatis
#logging.level.org.apache.ibatis=DEBUG
